# 整合各网站
SourceDic = [
    {
        "group": "A",
        "title":	"笔趣阁",
        "host":	"https://m.bqg119.com",
        "header": {
            "Accept": "application/json",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"
        },
        "query_url":	"https://m.bqg119.com/user/search.html?q=%s",
        "query_method":	0,
        "query_params":	"",
        "query_charset":	1,
        "book_name_xpath":	"//div[@class='result_title']/a",
        "book_mainpage_xpath":	"//div[@class='result_title']/a/@href",
        "book_author_xpath":	"//div[@class='result_time']",
        "enable_chapter_page":	0,
        "chapter_page_xpath":	"",
        "chapter_title_xpath":	"//li[@class='book-item']/a",
        "chapter_url_xpath":	"//li[@class='book-item']/a/@href",
        "enable_chapter_next":	0,
        "chapter_next_url_xpath":	"",
        "chapter_next_keyword_xpath":	"",
        "chapter_next_keyword":	"",
        "content_xpath":	"//*[@id=\"content\"]",
        "enable_content_next":	0,
        "content_next_url_xpath":	"",
        "content_next_keyword_xpath":	"",
        "content_next_keyword":	"",
        "content_filter_type":	0,
        "content_filter_keyword":	""
    },
    {
        "group": "B",
        "title":	"提莫書屋",
        "host":	"https://www.timotxt.com",
        "query_url":	"https://www.timotxt.com/search/%s",
        "query_method":	0,
        "query_params":	"",
        "query_charset":	1,
        "book_name_xpath":	"/html/body/div/div/div/section/ul/li/div[2]/h3/a",
        "book_mainpage_xpath":	"/html/body/div/div/div/section/ul/li/div[2]/h3/a/@href",
        "book_author_xpath":	"/html/body/div/div/div/section/ul/li/div[2]/span/text()",
        "enable_chapter_page":	1,
        "chapter_page_xpath":	"//*[@id=\"detail\"]/div[1]/div[2]/div/p/a[2]/@href",
        "chapter_title_xpath":	"/html/body/div/div/ul[2]/li/a",
        "chapter_url_xpath":	"/html/body/div/div/ul[2]/li/a/@href",
        "enable_chapter_next":	0,
        "chapter_next_url_xpath":	"",
        "chapter_next_keyword_xpath":	"",
        "chapter_next_keyword":	"",
        "content_xpath":	"//div[@class=\"content\"]/p",
        "enable_content_next":	0,
        "content_next_url_xpath":	"",
        "content_next_keyword_xpath":	"",
        "content_next_keyword":	"",
        "content_filter_type":	0,
        "content_filter_keyword":	""
    },
]
